% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Lecture Notes on Survival Analysis},
  pdfauthor={Thor Aspelund; Brynjólfur Gauti Jónsson},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage[]{natbib}
\bibliographystyle{apalike}

\title{Lecture Notes on Survival Analysis}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Course taught at the University of Iceland}
\author{Thor Aspelund \and Brynjólfur Gauti Jónsson}
\date{2020-03-04}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{preface}{%
\chapter{Preface}\label{preface}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{the-book}{%
\section{The Book}\label{the-book}}

These lecture notes are based on the book \href{https://www.crcpress.com/Modelling-Survival-Data-in-Medical-Research/Collett/p/book/9781439856789}{Modelling Survival Data in Medical Research by David Collett}

\includegraphics{https://images.tandf.co.uk/common/jackets/amazon/978143985/9781439856789.jpg}

\hypertarget{theory}{%
\section{Theory}\label{theory}}

Before you start you should be familiar with:

\begin{itemize}
\tightlist
\item
  Coffee
\item
  Etc
\item
  Etc
\end{itemize}

\hypertarget{software}{%
\section{Software}\label{software}}

We will primarily be writing R code using the RStudio GUI.

\hypertarget{setup-in-rstudio}{%
\section{Setup in RStudio}\label{setup-in-rstudio}}

This is our base setup. Further packages will be loaded in the individual lectures respectively.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse); }\KeywordTok{library}\NormalTok{(kableExtra); }\KeywordTok{library}\NormalTok{(cowplot); }\KeywordTok{library}\NormalTok{(scales); }\KeywordTok{library}\NormalTok{(janitor);}
\KeywordTok{theme\_set}\NormalTok{(}\KeywordTok{theme\_cowplot}\NormalTok{() }\OperatorTok{+}\StringTok{  }
\StringTok{              }\KeywordTok{background\_grid}\NormalTok{(}\DataTypeTok{major =} \StringTok{"xy"}\NormalTok{, }
                              \DataTypeTok{minor =} \StringTok{"xy"}\NormalTok{,}
                              \DataTypeTok{size.major =} \FloatTok{0.25}\NormalTok{,}
                              \DataTypeTok{size.minor =} \FloatTok{0.1}\NormalTok{) }\OperatorTok{+}
\StringTok{              }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"top"}\NormalTok{,}
                    \DataTypeTok{plot.margin =} \KeywordTok{margin}\NormalTok{(}\DecValTok{10}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{10}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\hypertarget{introduction-to-survival-analysis}{%
\chapter{Introduction to Survival Analysis}\label{introduction-to-survival-analysis}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(survival)}
\KeywordTok{library}\NormalTok{(tidyverse)}
\KeywordTok{library}\NormalTok{(epitools)}
\KeywordTok{library}\NormalTok{(survminer)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Gögnin fylgja með epitools pakkanum. Þá er nóg að virkja gögnin með data() skipun.}
\KeywordTok{data}\NormalTok{(wcgs)}
\NormalTok{wcgs}\OperatorTok{$}\NormalTok{behpat0f <{-}}\StringTok{ }\KeywordTok{factor}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{behpat0,}\DataTypeTok{levels=}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{,}\DataTypeTok{label=}\KeywordTok{c}\NormalTok{(}\StringTok{"A1"}\NormalTok{,}\StringTok{"A2"}\NormalTok{,}\StringTok{"B1"}\NormalTok{,}\StringTok{"B2"}\NormalTok{))}
\NormalTok{wcgs}\OperatorTok{$}\NormalTok{dibpat0f <{-}}\StringTok{ }\KeywordTok{factor}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{dibpat0,}\DataTypeTok{levels=}\DecValTok{0}\OperatorTok{:}\DecValTok{1}\NormalTok{,}\DataTypeTok{label=}\KeywordTok{c}\NormalTok{(}\StringTok{"B"}\NormalTok{,}\StringTok{"A"}\NormalTok{))}
\NormalTok{wcgs}\OperatorTok{$}\NormalTok{smoker <{-}}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{ncigs0}\OperatorTok{>}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{)}
\NormalTok{wcgs}\OperatorTok{$}\NormalTok{smokerf <{-}}\StringTok{ }\KeywordTok{factor}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{smoker,}\DataTypeTok{levels=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{),}\DataTypeTok{labels=}\KeywordTok{c}\NormalTok{(}\StringTok{"No"}\NormalTok{,}\StringTok{"Yes"}\NormalTok{))}
\NormalTok{wcgs}\OperatorTok{$}\NormalTok{heightcm <{-}}\StringTok{ }\NormalTok{wcgs}\OperatorTok{$}\NormalTok{height0}\OperatorTok{*}\FloatTok{2.54}
\NormalTok{wcgs}\OperatorTok{$}\NormalTok{weightkg <{-}}\StringTok{ }\NormalTok{wcgs}\OperatorTok{$}\NormalTok{weight0}\OperatorTok{*}\FloatTok{0.45359237}
\NormalTok{wcgs}\OperatorTok{$}\NormalTok{bmi <{-}}\StringTok{ }\NormalTok{wcgs}\OperatorTok{$}\NormalTok{weightkg }\OperatorTok{/}\StringTok{ }\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{heightcm}\OperatorTok{/}\DecValTok{100}\NormalTok{)}\OperatorTok{\^{}}\DecValTok{2}
\NormalTok{wcgs}\OperatorTok{$}\NormalTok{cholmmol =}\StringTok{ }\NormalTok{wcgs}\OperatorTok{$}\NormalTok{chol}\OperatorTok{/}\DecValTok{39}
\NormalTok{wcgs}\OperatorTok{$}\NormalTok{time169y <{-}}\StringTok{ }\NormalTok{wcgs}\OperatorTok{$}\NormalTok{time169}\OperatorTok{/}\FloatTok{365.24}
\CommentTok{\# restricted followup to 5 years}
\NormalTok{wcgs}\OperatorTok{$}\NormalTok{time169y5 <{-}}\StringTok{ }\KeywordTok{pmin}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{time169y,}\DecValTok{5}\NormalTok{)}
\NormalTok{wcgs}\OperatorTok{$}\NormalTok{chd695 <{-}}\StringTok{ }\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{chd69}\OperatorTok{==}\DecValTok{1} \OperatorTok{\&}\StringTok{ }\NormalTok{wcgs}\OperatorTok{$}\NormalTok{time169y }\OperatorTok{<=}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{inngangur}{%
\section{Inngangur}\label{inngangur}}

Efni dagsins í dag er myndræn framsetning i lifunargreiningu. Við munum skipta umfjölluninni í þrennt. Fyrst fjöllum við um skerðingu (e. censoring) af hverju hún stafar og hvernig við vinnum með hana. Því næst fjöllum við um Kaplan Meier metlinn, teiknum Kaplan Meier ferla og lærum að túlka þá og meta. Að lokum skoðum við hvernig meta má miðgildi lifunar (e. median survival) og skoðum tölfræðipróf til að kanna mun á lifunarferlum.

Við notum gagnasafnið \emph{wcgs} sem fylgir t.d. með \emph{epitools} pakkanum. WCGS stendur fyrir Western Collaborative Group Study. Nánari umfjöllun má sjá á \href{http://clinicaltrials.gov/show/NCT00005174}{ClincialTrials.gov}.

Í stuttu máli var 3154 karlmönnum á aldrinum 39 til 59 fylgt eftir í allt að 10 ár þangað til þeir fengu hjartasjúkdóm, eða létust, eða þeir urðu 70 ára eða eftirfylgni lauk af öðrum ástæðum.

\hypertarget{skeruxf0ing-censoring}{%
\section{Skerðing (censoring)}\label{skeruxf0ing-censoring}}

Meginmarkmið WCGS rannsóknarinnar var að skoða áhættuþætti fyrir hjartasjúkdómum og því eru hjartasjúkdómar aðalútkomubreytan okkar. Breytan \emph{chd69} segir til um hvort karlmennirnir fengu hjartasjúkdóm eða ekki.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{chd69)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1 
## 2897  257
\end{verbatim}

Við sjáum að alls fengu 257 karlmenn fengu hjartasjúkdóm á meðan rannsókninni stóð. Í lógistískri aðhvarfsgreiningu hefði okkur nægt að líta á þessa breytu sem útkomubreytuna okkar og látið þar við sitja. En fleiri upplýsingar er að finna i gögnunum okkar og því getum við gert betur.

Í fyrsta lagi höfum við upplýsingar um nákvæman dagafjölda frá því að eftirfylgdin hófst og þangað til maðurinn fékk hjartasjúkdóm og við getum tekið tillit til þess tíma í líkönunum okkar. Þannig getum við til dæmis skoðað þá sem fengu hjartasjúkdóm innan mjög skamms tíma.

Í öðru lagi er meginþorri gagnanna okkar \textbf{skertur} (e. censored), þ.e.a.s. eftirfylgdin stóð einungis yfir í takmarkaðan tíma og því höfum við ekki upplýsingar um hvort sumir mannanna hefðu mögulega þróað með sér hjartasjúkdóm eftir að eftirfylgdinni lauk. Skerðing getur verið af ýmsum ástæðum, maðurinn neitaði áframhaldandi þátttöku, rannsókninni lauk eða þá að hann dó af öðrum orsökum og hafði því ekki möguleika á að þróa með sér hjartasjúkdóm í framhaldinu. Til eru aðferðir til að skoða margs konar útkomur samtímis (t.d. bæði hjartaáföll og dauða) og er þá talað um \emph{samkeppni áhættu} (e. competing risk). Þær aðferðir eru utan efni þessa námskeiðs.

Skerðing getur verið frá vinstri (þ.e.a.s. eftirfylgni hófst ekki fyrr en á ákveðnum tímapunkti) eða frá hægri (eftirfylgni lauk á ákveðnum tímapunkti) eða á bili (eftirfylgni var eingöngu á ákveðnu tímabili). Í langflestum tilvikum er unnið með skerðingu frá hægri og því munum við bara fjalla um hana hér.

Á sama hátt og viðbótarupplýsingar eru fólgnar í því hversu fljótt einstaklingur fékk hjartasjúkdóm eru einnig heilmiklar upplýsingar fólgnar i því hversu lengi honum var fylgt eftir \emph{án þess} að hann fengi hjartasjúkdóm. Því skiptir tími fram að skerðingu jafn miklu máli og tími fram að hjartasjúkdómi.

Í R tvinnum við saman þessar upplýsingar með því að búa til breytu af gerðinni \textbf{lifunarhlutur} (e. survival object). Við búum hann til með skipuninni \emph{Surv} sem er í pakkanum \emph{survival} og mötum á tveimur breytum:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Hve langur tími leið fram að atburði/þangað til eftirfylgd lauk
\item
  Hvort atburður eða skerðing átti sér stað á þeim tímapunkti.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lifunar.hlutur <{-}}\StringTok{ }\KeywordTok{Surv}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{time169, wcgs}\OperatorTok{$}\NormalTok{chd69)}
\end{Highlighting}
\end{Shaded}

Skoðum nánar fyrstu sex mælingarnar í lifunarhlutnum:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(lifunar.hlutur)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1664+ 3071+ 3071+ 3064+ 1885  3102+
\end{verbatim}

Fyrsta mælingin er 1664, 0. Plúsinn gefur til kynna að honum var fylgt eftir í 1664 daga án þess að til atburðar kæmi og því er mælingin skert. Fimmta mælinginin, 1885, 1 hefur hins vegar engan plús sem gefur til kynna að maðurinn fékk hjartasjúkdóm eftir 1885, 1 daga.

\hypertarget{kaplan-meier-metillinn}{%
\section{Kaplan Meier metillinn}\label{kaplan-meier-metillinn}}

Kaplan Meier metilinn er ein langmest notaða tölfræðiaðferðin þegar framkvæmd er lifunargreining, meðal annars vegna þess að á honum byggja svo kölluð Kaplan-Meier gröf sem eru ein algengasta leiðin til að lýsa lifunargögnum. Okkur þykir því ástæða til að skoða hann í kjölinn.

Fyrst skulum við kynna til sögunnar svokallað \textbf{lifunarfall} (e. survival curve). Lifunarfallið er yfirleitt táknað með \(S(t)\) og túlkun fallsins er svohljóðandi

\[ 
S(t) = \text{Líkur þess að einstaklingur fá ekki atburð fram að tíma $t$.}
\]

Lifunarfallið miðar alltaf við einhvern tiltekinn atburð. Oft er sá atburður dauði, en hann er einnig mjög oft eitthvað annað eins og til dæmis greining á sjúkdómi. Í því tilviki er stundum talað um ``sjúkdómslausa lifun'' eða ``atburðarlausa lifun'' til að skerpa á að lifunin eigi ekki við um líf og dauða, heldur lifun án þess að hafa fengið tiltekinn atburð, sem í þessu tilviki er greining á sjúkdóm. Lifunarfallið gefur okkur þá líkurnar á því að hafa ekki fengið sjúkdóm innan tiltekins tíma.

Í okkar tilfelli væri \(S(365)\) líkur þess að einstaklingur fái ekki hjartasjúkdóm innan 365 daga. Ef ekki væri fyrir skerðingu væri lítill vandi að meta hvert það gildi væri, sem við samkvæmt venju köllum \(\hat S(365)\). Besta matið á \(\hat S(365)\) væri einfaldlega fjöldi þeirra sem fengu hjartasjúkdóm innan 365 daga af allri heildinni. En skerðingarinnar vegna vandast málin.

Kaplan Meier metilinn er stærðfræðileg regla til að meta \(\hat S(t)\). Hann er metinn á sérhverjum tímapunkti þegar \emph{atburður} á sér stað (en ekki skerðing). Í gögnunum okkar fengu 257 karlmenn hjartasjúkdóm svo þessir tímapunktar eru að hámarki 257. Við nánari athugun reynast stundum fleiri en einn karlmaður fá hjartasjúkdóm eftir jafnlangan tíma svo tímapunktarnir eru alls 248. Ef við gefum þeim heiti eftir stærðarröð þeirra, \(t_1, \ldots , t_{248}\), þá væri:

\begin{itemize}
\tightlist
\item
  \(t_1 =\) 18, sem er sá tímapunktur þegar fyrsti maðurinn fékk hjartasjúkdóm,
\item
  \(t_2 =\) 21 væri sá tímapunktur þegar næsti maður fékk hjartasjúkdóm
\item
  \(t_{248} =\) 3229, væri að lokum sá tímapunktur þegar síðasti maðurinn fékk hjartasjúkdóm.
\end{itemize}

Kaplan Meier metilinn er metinn á sérhverjum þessara 248 tímapunkta. Formúla metilsins er

\[ \hat S(t) = \Pi_{i=1}^k \left( 1- \frac{d_i}{n_i} \right)\]

þar sem \(d_i\) táknar fjölda þeirra sem fengu atburðinn á tímapunkti \(i\) en \(n_i\) er fjöldi þeirra sem er \emph{enn í áhættu} að fá atburðinn á tímapunkti \(i\), þ.e.a.s. hafa hvorki fengið atburðinn, né verið skertir.

Í fyrsta tímapunktinum er Kaplan Meier metillinn hreinlega hlutfall þeirra sem ekki var kominn með hjartasjúkdóm af þeim sem ekki voru orðnir skertir á þeim tímapunkti (þ.e.a.s. af þeim sem voru enn í eftirfylgd). Fyrir næsta tímapunkt þarf að reikna einn mínus hlutfall fjölda þeirra sem fékk hjartasjúkdóm \emph{á þeim tímapunkti} af þeim sem enn voru í eftirfylgd á þeim tímapunkti og margfalda það gildi við síðasta reiknaða Kaplan-Meier gildið. Þannig er haldið áfram koll af kolli fyrir alla tímapunktana.

Skoðum nú fyrstu gildin handvirkt. Fyrir fyrsta tímapunktinn, \(t_1\), sem var \(t=18\), skoðum við hversu margir eru enn í eftirfylgd á þeim tímapunkti:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{time169}\OperatorTok{>=}\DecValTok{18}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3154
\end{verbatim}

og hversu margir þeirra höfðu ekki fengið hjartasjúkdóm á þeim tímapunkti

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{time169}\OperatorTok{>=}\DecValTok{18}\NormalTok{) }\OperatorTok{{-}}\StringTok{ }\KeywordTok{sum}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{time169}\OperatorTok{<=}\DecValTok{18}\OperatorTok{\&}\NormalTok{wcgs}\OperatorTok{$}\NormalTok{chd69}\OperatorTok{==}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3153
\end{verbatim}

Kaplan-Meier matið á tímapunkti \(t=18\), er því hlutfall þessara tveggja talna, eða \(3153/3154\) sem er 99.97 prósent.

Fyrir næsta tímapunktinn, \(t_2\), sem var \(t=21\), skoðum við hversu margir eru enn í eftirfylgd á þeim tímapunkti

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{time169}\OperatorTok{>=}\DecValTok{21}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3153
\end{verbatim}

og hversu margir þeirra fengu hjartasjúkdóm á þeim tímapunkti

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(wcgs}\OperatorTok{$}\NormalTok{time169}\OperatorTok{==}\DecValTok{21}\OperatorTok{\&}\NormalTok{wcgs}\OperatorTok{$}\NormalTok{chd69}\OperatorTok{==}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1
\end{verbatim}

Hlutfallið á tímapunkti \(t_2\) er því

\(1 - d_2/n_2 = 1 - 1/3153 = 3152/3153\)

Kaplan Meier gildið á tímapunkti \(t_2\) er þá það gildi, margfaldað með síðasta reiknaða gildi eða \(3152/3153 \cdot 3153/3154 = 3152/3154\) sem er 99.94 prósent.

Svona er haldið áfram koll af kolli fyrir alla 248 tímapunktana.

Kaplan Meier matið er eingöngu metið á þeim tímapunktum þegar atburður á sér stað. Ef við viljum meta lifunarfallið á tímapunktum sem lenda á milli þessara gilda notum við Kaplan-Meier matið fyrir næsta tímapunkt á undan.

\hypertarget{kaplan-meier-gruxf6f}{%
\section{Kaplan Meier gröf}\label{kaplan-meier-gruxf6f}}

Kaplan Meier gröf eru langalgengasta myndræna framsetningin á lifunargögnum. Þau eru leið til að lýsa lifunarfallinu myndrænt, þ.e.a.s. hversu hátt hlutfall þátttakanda hefur ekki fengið atburð eftir því sem tíminn líður. Gröfin teikna Kaplan Meier matið í sérhverjum tímapunkti og flatar línur milli punktanna. Gröfin eru látin ``falla'' á þeim tímapunktum sem atburðir eiga sér stað í samræmi við það hvernig matið er reiknað.

Fyrst um sinn skulum við skoða Kaplan-Meier graf fyrir fyrstu 100 dagana. Það má sjá hér fyrir neðan. Notum tímann í árum \emph{time169y}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{kmfit <{-}}\StringTok{ }\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(time169,chd69)}\OperatorTok{\textasciitilde{}}\DecValTok{1}\NormalTok{,}\DataTypeTok{data=}\NormalTok{wcgs)}
\NormalTok{km.plot <{-}}\StringTok{ }\KeywordTok{ggsurvplot}\NormalTok{(kmfit,}\DataTypeTok{risk.table =}\NormalTok{ T,}\DataTypeTok{break.time.by=}\DecValTok{10}\NormalTok{,}\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{110}\NormalTok{),}
                      \DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\FloatTok{0.99}\NormalTok{,}\DecValTok{1}\NormalTok{)) }
\NormalTok{km.plot }
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Survival_Analysis_files/figure-latex/unnamed-chunk-11-1}

Grafið byrjar í \(y=1.00\), þegar \(t=0\), enda hefur enginn fengið hjartasjúkdóm við byrjun rannsóknarinnar. Inn á grafið er ég búin að teikna punktalínur þar sem fyrsta ``fallið'' verður. En það er einmitt við \(t=18\) þegar fyrsti maðurinn fékk hjartasjúkdóm. Þar dettur línan úr 1.00 í 0.9997 eins og við vorum búin að reikna. Næsta ``fall'' verður við \(t=21\) þegar næsti maður fékk hjartaáfall og svo koll af kolli.

Stækkum nú tímarammann okkar og skoðum Kaplan-Meier graf fyrir fyrstu 365 dagana:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{kmfit <{-}}\StringTok{ }\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(time169,chd69)}\OperatorTok{\textasciitilde{}}\DecValTok{1}\NormalTok{,}\DataTypeTok{data=}\NormalTok{wcgs)}
\NormalTok{km.plot <{-}}\StringTok{ }\KeywordTok{ggsurvplot}\NormalTok{(kmfit,}\DataTypeTok{risk.table =}\NormalTok{ T,}\DataTypeTok{break.time.by=}\DecValTok{30}\NormalTok{,}\DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{365}\NormalTok{),}
                      \DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\FloatTok{0.99}\NormalTok{,}\DecValTok{1}\NormalTok{)) }
\NormalTok{km.plot }
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Survival_Analysis_files/figure-latex/unnamed-chunk-12-1}

Núna hafa nokkur lóðrétt strik bæst við (sem eru í raun plúsar ef nána er að gáð). Þær merkingar eru þar sem skerðingar eiga sér stað, á þeim tímapunktum hefur einhver þátttakandi hætt í eftirfylgd af einhverjum ástæðum. Munið að Kaplan-Meier metilinn er bara metinn á þeim tímapunktum sem atburðir eiga sér stað, sem í þessu tilfelli eru hjartasjúkdómar, svo grafið breytist ekki á þeim tímapunkti, plúsarnir bætast bara við. Sum tímarit kjósa að fá Kaplan-Meier gröf með slíkum merkingum þegar skerðingar eru en önnur ekki. Það er ætíð hægt að stilla til í R.

Skipunin \textbf{survfit} metur Kaplan Meier metilinn fyrir okkur. Við mötum hana með lifunarhlut til vinstri en hægra megin koma flokkarnir sem við skiptum gögnunum eftir. Til að byrja með höfum við enga skiptingu á gögnunum og setjum þess vegna bara 1 hægra megin i skipunina.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{kmfit <{-}}\StringTok{ }\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(time169,chd69)}\OperatorTok{\textasciitilde{}}\DecValTok{1}\NormalTok{,}\DataTypeTok{data=}\NormalTok{wcgs)}
\end{Highlighting}
\end{Shaded}

\hypertarget{kaplan-meier-gruxf6f-eftir-huxf3pum}{%
\section{Kaplan Meier gröf eftir hópum}\label{kaplan-meier-gruxf6f-eftir-huxf3pum}}

Kaplan Meier gröf eru kjörin til að sýna mun á lifunarfallinu eftir hópum. Hér liggur beint við að skoða mun á lifun án hjartasjúkdóms eftir persónuleikagerð. Þá setjum við nafnið á þeirri breytu hægra megin í survfit skipunina þar sem 1 var áður fyrr.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{kmfit}\FloatTok{.2}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(time169,chd69)}\OperatorTok{\textasciitilde{}}\NormalTok{dibpat0f,}\DataTypeTok{data=}\NormalTok{wcgs)}
\end{Highlighting}
\end{Shaded}

Hér breytum við skalanum í ár og skoðum tíma að hjartasjúkdómi eftir persónuleika A og B.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{km.plot}\FloatTok{.2}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{ggsurvplot}\NormalTok{(kmfit}\FloatTok{.2}\NormalTok{,}\DataTypeTok{risk.table =}\NormalTok{ T,}\DataTypeTok{xscale=}\FloatTok{365.35}\NormalTok{,}
                        \DataTypeTok{break.time.by=}\FloatTok{365.25}\NormalTok{,}\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\FloatTok{0.8}\NormalTok{,}\DecValTok{1}\NormalTok{),}\DataTypeTok{tables.height=}\FloatTok{0.3}\NormalTok{) }
\NormalTok{km.plot}\FloatTok{.2} 
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Survival_Analysis_files/figure-latex/unnamed-chunk-15-1}

Á þessari mynd virðist vera mikill munur á tíðni hjartasjúkdóma eftir persónuleikagerð. Blái ferillinn, sem táknar persónuleikagerð A, er allur fyrir neðan rauða ferilinn sem táknar persónuleikagerð B. Þar af leiðandi metum við að lifunarfallið sé lægra, þ.e. að líkur þess að vera \textbf{án} hjartasjúkdóms eru minni, sem þýðir að líkurnar á því að \textbf{fá} hjartasjúkdóm eru hærri. Næst munum við sjá leið til að prófa hvort sá munur sé tölfræðilega marktækur.

\hypertarget{miuxf0gildi-lifunar-og-logrank-pruxf3f}{%
\section{Miðgildi lifunar og logrank próf}\label{miuxf0gildi-lifunar-og-logrank-pruxf3f}}

Algeng leið til að lýsa lifun er svokallað \textbf{miðgildi lifunar} (median survival). Það er sú tímalengd \(T\) þar sem \(S(T)\) verður minna en 50\%. Með orðum er það sá tímapunktur þegar helmingur þátttakandanna ættu að hafa fengið atburðinn. Með því að skrifa út nafnið á lifunarhlutnum okkar fæst mat á miðgildi lifunar ásamt 95\% öryggisbili.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{kmfit}\FloatTok{.2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call: survfit(formula = Surv(time169, chd69) ~ dibpat0f, data = wcgs)
## 
##               n events median 0.95LCL 0.95UCL
## dibpat0f=B 1565     79     NA      NA      NA
## dibpat0f=A 1589    178     NA      NA      NA
\end{verbatim}

Hér vandast málið! Við sjáum bara NA. Ástæða þess er sú að karlmönnunum i WCGS rannsókninni var ekki fylgt eftir svo lengi að helmingur þeirra hefði þróað með sér hjartasjúkdóm. Í slíkum tilvikum er ekki við hæfi að lýsa lifunarfallinu með miðgildi lifunar, heldur er oft miðað við eins árs, eða fimm ára lifun, svo dæmi séu tekin. Með eins árs lifun er átt við matinu á lifunarfallinu þegar ár er liðið. Þegar lifun er mæld í dögum eins og hjá okkur er það þá \(\hat S(365.25)\). Að sama skapi væri matið á fimm ára lifun \(\hat S(1826.25)\). (Ath 5*365.25=18625.)

Það er auðvelt að biðja R um mat á lifunarfallinu fyrir hvaða tímapunkt sem er. Það er gert með skipuninni \emph{summary()} sem er mötuð með \emph{times()} þar sem tímapunktarnir eru skilgreindir.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(kmfit}\FloatTok{.2}\NormalTok{, }\DataTypeTok{times=}\KeywordTok{c}\NormalTok{(}\FloatTok{365.25}\NormalTok{,}\DecValTok{5}\OperatorTok{*}\FloatTok{365.25}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call: survfit(formula = Surv(time169, chd69) ~ dibpat0f, data = wcgs)
## 
##                 dibpat0f=B 
##  time n.risk n.event survival  std.err lower 95% CI upper 95% CI
##   365   1561       2    0.999 0.000904        0.997        1.000
##  1826   1433      36    0.975 0.004026        0.967        0.983
## 
##                 dibpat0f=A 
##  time n.risk n.event survival std.err lower 95% CI upper 95% CI
##   365   1574      13    0.992 0.00226        0.987        0.996
##  1826   1348      88    0.934 0.00635        0.922        0.947
\end{verbatim}

Við sjáum að matið á 365 daga (1 árs) lifun fyrir persónuleikagerð B er 0.99 með 95\% ÖB (0.997-1.00) en matið á 365 daga lifun fyrir persónuleikagerð A er 0.992 með 95\% ÖB (0.987-0.996). Í neðri línunum sjáum við matið á 1825 (5 ára) lifun. Það er 0.975 (0.967-0.983) fyrir persónuleikagerð B en 0.934 (0.922-0.947) fyrir persónuleikagerð A.

Allt að ofan bendir til þess að það sé munur í tíðni hjartasjúkdóma eftir persónuleikagerðum. Ein leið til að prófa þann mun er með \textbf{logrank prófi} en það prófar hvort munur sé á tveimur lifunarföllum. Skipunin er einfaldlega \emph{survdiff} og rithátturinn er nákvæmlega sá sami og fyrir \emph{surffit}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{survdiff}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(time169,chd69)}\OperatorTok{\textasciitilde{}}\NormalTok{dibpat0f,}\DataTypeTok{data=}\NormalTok{wcgs)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## survdiff(formula = Surv(time169, chd69) ~ dibpat0f, data = wcgs)
## 
##               N Observed Expected (O-E)^2/E (O-E)^2/V
## dibpat0f=B 1565       79      131      20.5      41.8
## dibpat0f=A 1589      178      126      21.3      41.8
## 
##  Chisq= 41.8  on 1 degrees of freedom, p= 1e-10
\end{verbatim}

Og mikið rétt! Munurinn reyndist marktækur, p-gildið er \(1 \cdot 10^{-10}\). Logrank prófið er líka hægt að nota þegar hóparnir eru fleiri en tveir og prófa það þá núlltilgátuna hvort allir ferlarnir séu eins.

Núlltilgátan er að atburðir séu jafn tíðir milli hópanna. Taflan sýnir \emph{Expected} eða væntanlegan fjölda miðað við þá tilgátu. En gögnin sýna (\emph{Observed}) að atburðir eru færri í B hóp og fleiri í A hóp en búast mætti við ef tilgátan væri sönn. Við höfnum þeirri tilgátu og drögum þá ályktun að tíðni atburða sé meiri í A hóp.

\hypertarget{vuxedti-auxf0-varast-og-breyting-uxe1-tuxedmaskala}{%
\section{Víti að varast og breyting á tímaskala}\label{vuxedti-auxf0-varast-og-breyting-uxe1-tuxedmaskala}}

Algeng en alvarleg mistök sem geta gerst er að ruglast á því hvort atburður eða skerðing eigi að vera táknuð með 0 eða 1. Það er þó auðvelt að bera kennsl á þvi mistök því þá stefna ferlarnir í Kaplan Meier gröfunum beinustu leið niður undir restina og enda alltaf í núlli. Hér er dæmi um slíkt.

Hvað gerist ef ruglast er á atburði og skerðingu!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{km.fit}\FloatTok{.3}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(time169,chd69}\OperatorTok{==}\DecValTok{0}\NormalTok{)}\OperatorTok{\textasciitilde{}}\NormalTok{dibpat0f,}\DataTypeTok{data=}\NormalTok{wcgs)}
\KeywordTok{ggsurvplot}\NormalTok{(km.fit}\FloatTok{.3}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Survival_Analysis_files/figure-latex/unnamed-chunk-19-1}

Að lokum langar okkur að sýna ykkur einfalda leið til að breyta tímaskalanum svo hann sé í árum en ekki dögum. Það er einfaldlega með því að deila í dagafjöldann með 365 þegar lifun skilgreindur. Annað hvort með því að búa til nýja breytu eins og time169y fyrir ofan eða inní survfit.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{km.fit}\FloatTok{.4}\NormalTok{ <{-}}\StringTok{ }\KeywordTok{survfit}\NormalTok{(}\KeywordTok{Surv}\NormalTok{(time169}\OperatorTok{/}\FloatTok{365.25}\NormalTok{,chd69) }\OperatorTok{\textasciitilde{}}\StringTok{ }\NormalTok{dibpat0f,}\DataTypeTok{data=}\NormalTok{wcgs)}
\KeywordTok{ggsurvplot}\NormalTok{(km.fit}\FloatTok{.4}\NormalTok{,}\DataTypeTok{ylim=}\KeywordTok{c}\NormalTok{(}\FloatTok{0.8}\NormalTok{,}\DecValTok{1}\NormalTok{))  }
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{Survival_Analysis_files/figure-latex/unnamed-chunk-20-1}

\hypertarget{some-non-parametric-procedures}{%
\chapter{Some Non-Parametric Procedures}\label{some-non-parametric-procedures}}

Here is a review of existing methods.

\hypertarget{the-cox-regression-model}{%
\chapter{The Cox Regression Model}\label{the-cox-regression-model}}

We describe our methods in this chapter.

\hypertarget{model-checking-in-the-cox-regression-model}{%
\chapter{Model Checking in the Cox Regression Model}\label{model-checking-in-the-cox-regression-model}}

Some \emph{significant} applications are demonstrated in this chapter.

\hypertarget{example-one}{%
\section{Example one}\label{example-one}}

\hypertarget{example-two}{%
\section{Example two}\label{example-two}}

\hypertarget{parametric-proportional-hazards-models}{%
\chapter{Parametric Proportional Hazards Models}\label{parametric-proportional-hazards-models}}

We have finished a nice book.

\hypertarget{time-dependent-variables-and-covariates}{%
\chapter{Time-Dependent Variables and Covariates}\label{time-dependent-variables-and-covariates}}

asdad

\hypertarget{competing-risks}{%
\chapter{Competing Risks}\label{competing-risks}}

asdad

  \bibliography{book.bib,packages.bib}

\end{document}
